import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * 每套教程一个独立侧边栏，均基于 docs/ 下对应目录结构自动生成。
 */
const sidebars: SidebarsConfig = {
  pythonSidebar: [{type: 'autogenerated', dirName: 'python'}],
  goSidebar: [{type: 'autogenerated', dirName: 'go'}],
  mysqlSidebar: [{type: 'autogenerated', dirName: 'mysql'}],
  redisSidebar: [{type: 'autogenerated', dirName: 'redis'}],
  fastapiSidebar: [{type: 'autogenerated', dirName: 'fastapi'}],
  sqlalchemySidebar: [{type: 'autogenerated', dirName: 'sqlalchemy'}],
  devopsSidebar: [{type: 'autogenerated', dirName: 'devops'}],
};

export default sidebars;
